# -*- coding: utf-8 -*-
"""jinu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A5lNqWD6Ra5NjY1hW_hbEwNZKkJnxRPi
"""

print("hello")